name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py37_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - alabaster=0.7.12=py37_0
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py37_0
  - anaconda-navigator=1.9.12=py37_0
  - anaconda-project=0.9.1=pyhd3eb1b0_1
  - applaunchservices=0.2.1=py_0
  - appnope=0.1.2=py37hecd8cb5_1001
  - appscript=1.1.2=py37h9ed2024_0
  - argh=0.26.2=py37_0
  - argon2-cffi=20.1.0=py37haf1e3a3_1
  - asn1crypto=1.4.0=py_0
  - astroid=2.4.2=py37_0
  - astropy=4.2=py37h9ed2024_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.4=py_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.0=pyhd3eb1b0_2
  - backports.functools_lru_cache=1.6.1=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - bitarray=1.6.3=py37h9ed2024_1
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blosc=1.20.1=hab81aa3_0
  - bokeh=2.2.3=py37_0
  - boto=2.49.0=py37_0
  - bottleneck=1.3.2=py37hf1fa96c_1
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py37h9ed2024_1003
  - brunsli=0.1=h23ab428_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2021.1.19=hecd8cb5_0
  - certifi=2020.12.5=py37hecd8cb5_0
  - cffi=1.14.4=py37h2125817_0
  - chardet=4.0.0=py37hecd8cb5_1003
  - charls=2.1.0=hb1e8313_2
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.9.2=py37hecd8cb5_0
  - conda-build=3.18.11=py37_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.7.2=py37h22f3db7_0
  - conda-verify=3.4.2=py_1
  - contextlib2=0.6.0.post1=py_0
  - cryptography=3.3.1=py37hbcfaee0_0
  - curl=7.71.1=hb0a8c7a_1
  - cycler=0.10.0=py37_0
  - cython=0.29.21=py37h23ab428_0
  - cytoolz=0.11.0=py37haf1e3a3_0
  - dask=2021.1.1=pyhd3eb1b0_0
  - dask-core=2021.1.1=pyhd3eb1b0_0
  - dbus=1.13.18=h18a8e69_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.6.0=pyhd3eb1b0_0
  - diff-match-patch=20200713=py_0
  - distributed=2021.1.1=py37hecd8cb5_1
  - docutils=0.16=py37_1
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.10=hb1e8313_2
  - fastcache=1.1.0=py37h1de35cc_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - flake8=3.8.4=py_0
  - flask=1.1.2=pyhd3eb1b0_0
  - freetype=2.10.4=ha233b18_0
  - fsspec=0.8.3=py_0
  - future=0.18.2=py37_1
  - get_terminal_size=1.0.0=h7520d66_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - gevent=21.1.1=py37h9ed2024_1
  - giflib=5.1.4=h1de35cc_1
  - glib=2.66.1=h9bbe63b_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h23ab428_2
  - gmpy2=2.0.8=py37h6ef4df4_2
  - greenlet=1.0.0=py37h23ab428_2
  - h5py=2.10.0=py37h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.1=py_0
  - html5lib=1.1=py_0
  - icu=58.2=h0a44026_3
  - idna=2.10=pyhd3eb1b0_0
  - imagecodecs=2021.1.11=py37h2ea9c00_1
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2019.4=233
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.20.0=py37h01d92e1_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - isort=5.7.0=pyhd3eb1b0_0
  - itsdangerous=1.1.0=py37_0
  - jbig=2.1=h4d881f8_0
  - jdcal=1.4.1=py_0
  - jedi=0.14.1=py37_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py37hecd8cb5_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_server=1.2.0=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=haf1e3a3_2
  - keyring=22.0.1=py37hecd8cb5_0
  - kiwisolver=1.3.1=py37h23ab428_0
  - krb5=1.18.2=h75d18d8_0
  - lazy-object-proxy=1.4.3=py37h9ed2024_2
  - lcms2=2.11=h92f6f08_0
  - lerc=2.2.1=h23ab428_0
  - libaec=1.0.4=hb1e8313_1
  - libarchive=3.4.2=haa3ed63_0
  - libcurl=7.71.1=h8a08a2b_1
  - libcxx=10.0.0=1
  - libdeflate=1.7=h9ed2024_5
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - liblief=0.10.1=h0a44026_0
  - libllvm10=10.0.1=h76017ad_5
  - libllvm9=9.0.1=h21ff451_1
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h0a44026_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.1.0=hcb84e12_1
  - libwebp=1.0.1=hd73b212_0
  - libxml2=2.9.10=h7cdb67c_3
  - libxslt=1.1.34=h83b36ba_0
  - libzopfli=1.0.3=hb1e8313_0
  - llvm-openmp=10.0.0=h28b9765_0
  - llvmlite=0.34.0=py37h739e7dc_4
  - locket=0.2.1=py37hecd8cb5_1
  - lxml=4.6.2=py37h26b266a_0
  - lz4-c=1.9.3=h23ab428_0
  - lzo=2.10=haf1e3a3_2
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.3.2=hecd8cb5_0
  - matplotlib-base=3.3.2=py37h181983e_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.2.0=py37hc64f4ea_0
  - mkl_random=1.1.1=py37h959d312_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpmath=1.1.0=py37_0
  - msgpack-python=1.0.2=py37hf7b0b51_1
  - multipledispatch=0.6.0=py37_0
  - navigator-updater=0.2.1=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=h0a44026_1
  - networkx=2.5=py_0
  - nltk=3.5=py_0
  - nose=1.3.7=pyhd3eb1b0_1006
  - notebook=6.2.0=py37hecd8cb5_0
  - numexpr=2.7.2=py37h16bde0e_0
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openpyxl=3.0.6=pyhd3eb1b0_0
  - openssl=1.1.1i=h9ed2024_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.1=py37hb2f4e1b_0
  - pandoc=2.11=h0dc7051_0
  - pandocfilters=1.4.3=py37hecd8cb5_1
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - path=15.1.0=py37hecd8cb5_0
  - path.py=12.5.0=0
  - pathlib2=2.3.5=py37hecd8cb5_2
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py37_0
  - pcre=8.44=hb1e8313_0
  - pep8=1.7.1=py37_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py37h5270095_0
  - pip=20.3.3=py37hecd8cb5_0
  - pkginfo=1.7.0=py37hecd8cb5_0
  - pluggy=0.13.1=py37_0
  - ply=3.11=py37_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - psutil=5.8.0=py37h9ed2024_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py37haf313ee_0
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py37h9ed2024_0
  - pycparser=2.20=py_2
  - pycrypto=2.6.1=py37haf1e3a3_10
  - pycurl=7.43.0.6=py37hddc9c9b_0
  - pydocstyle=5.1.1=py_0
  - pyerfa=1.7.1.1=py37h9ed2024_1
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.7.4=pyhd3eb1b0_0
  - pylint=2.6.0=py37_0
  - pyodbc=4.0.30=py37h0a44026_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.17.3=py37haf1e3a3_0
  - pysocks=1.7.1=py37hecd8cb5_0
  - pytables=3.6.1=py37h5bccee9_0
  - pytest=6.2.2=py37hecd8cb5_2
  - python=3.7.6=h359304d_2
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.31.7=py37_0
  - python-libarchive-c=2.9=pyhd3eb1b0_0
  - python.app=2=py37_10
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py37haf1e3a3_2
  - pyyaml=5.4.1=py37h9ed2024_1
  - pyzmq=20.0.0=py37h23ab428_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=1.0.1=py_0
  - qtconsole=5.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.25.1=pyhd3eb1b0_0
  - ripgrep=12.1.1=0
  - rope=0.18.0=py_0
  - rtree=0.9.4=py37_1
  - ruamel_yaml=0.15.87=py37haf1e3a3_1
  - scikit-image=0.17.2=py37h81aa140_0
  - scikit-learn=0.23.2=py37h959d312_0
  - scipy=1.6.0=py37h2515648_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37hecd8cb5_0
  - simplegeneric=0.8.1=py37_2
  - singledispatch=3.4.0.3=py_1001
  - sip=4.19.8=py37h0a44026_0
  - six=1.15.0=py37hecd8cb5_0
  - snappy=1.1.8=hb1e8313_0
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.3.0=pyhd3eb1b0_0
  - soupsieve=2.1=pyhd3eb1b0_0
  - sphinx=3.4.3=pyhd3eb1b0_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.0.1=py37_0
  - spyder-kernels=1.8.1=py37_0
  - sqlalchemy=1.3.23=py37h9ed2024_0
  - sqlite=3.33.0=hffcf06c_0
  - statsmodels=0.12.1=py37h9ed2024_0
  - sympy=1.7.1=py37hecd8cb5_0
  - tbb=2020.3=h879752b_0
  - tblib=1.7.0=py_0
  - terminado=0.9.2=py37hecd8cb5_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2021.1.14=pyhd3eb1b0_1
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py37h9ed2024_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typed-ast=1.4.2=py37h9ed2024_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - ujson=4.0.2=py37h23ab428_0
  - unicodecsv=0.14.1=py37_0
  - unixodbc=2.3.9=haf1e3a3_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - watchdog=1.0.2=py37h9ed2024_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h9ed2024_0
  - wurlitzer=2.0.1=py37_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=1.3.7=pyhd3eb1b0_0
  - xlwings=0.22.0=py37hecd8cb5_0
  - xlwt=1.3.0=py37_0
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.30.0=py_0
  - zeromq=4.3.3=hb1e8313_3
  - zfp=0.5.5=h23ab428_4
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zope=1.0=py37_1
  - zope.event=4.5.0=py37_0
  - zope.interface=5.2.0=py37h9ed2024_0
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - allosaurus==0.4.3
    - aniso8601==8.1.1
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - asciinema==2.0.2
    - audioread==2.1.8
    - awkward1==0.2.27
    - dataclasses==0.6
    - dtw==1.4.0
    - dtw-python==1.1.6
    - editdistance==0.5.3
    - fairseq==1.0.0a0+6225dcc
    - feather-format==0.4.1
    - flask-ask==0.8.8
    - hydra-core==1.0.5
    - importlib-resources==5.1.0
    - librosa==0.8.0
    - munkres==1.1.2
    - numba==0.43.0
    - omegaconf==2.0.6
    - panphon==0.17
    - pooch==1.1.1
    - portalocker==1.7.0
    - pyarrow==1.0.0
    - pypyr==4.5.0
    - regex==2020.6.8
    - resampy==0.2.2
    - sacrebleu==1.5.0
    - sharedarray==3.2.1
    - soundfile==0.10.3.post1
    - torch==1.6.0
    - torchaudio==0.6.0
    - torchvision==0.6.1
    - webrtcvad==2.0.10
prefix: /Users/fauxneticien/opt/anaconda3
